version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserverproducts
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=TuPassword123!
    ports:
      - "1433:1433"
    restart: always
